name: Apollo Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: apollographql/rover-actions/install-rover-cli@v1
      - uses: apollographql/rover-actions/subgraph-publish@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ secrets.APOLLO_GRAPH_REF }}
          name: products
          schema: ./products.graphql
          routing-url: http://ignored
      - uses: apollographql/rover-actions/subgraph-publish@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ secrets.APOLLO_GRAPH_REF }}
          name: teams
          schema: ./teams.graphql
          routing-url: http://ignored
